#########################################################################
#    Description: This file contains the configuration for the MSCR     #
#########################################################################

