#########################################################################
#    Description: This file contains the configuration for the MSCR     #
#########################################################################
MSCRProperties:
  E: 3000000.0
  I: 1.407094173220649e-13
  L: 0.024
  N: 1000
  A: 9.27093388283651e-07
  H0: 180.0e-3
  hatM:
  - 1.0
  - 0.0
  - 0.0
  normM: 80000.0
  r: 0.000543
