(cl:defpackage magmed_msgs-srv
  (:use )
  (:export
   "SELFCOLLISIONCHECK"
   "<SELFCOLLISIONCHECK-REQUEST>"
   "SELFCOLLISIONCHECK-REQUEST"
   "<SELFCOLLISIONCHECK-RESPONSE>"
   "SELFCOLLISIONCHECK-RESPONSE"
  ))

