####################################
# YoloV5模型权重路径
weight:  "weights/best.pt"
# 输入图像的尺寸
input_size: 640
# 类别个数
class_num:  16
# 标签名称
class_name: ['dog', 'person', 'cat', 'tv', 'car', 'meatballs', 'marinara sauce', 'tomato soup', 'chicken noodle soup', 'french onion soup', 'chicken breast', 'ribs', 'pulled pork', 'hamburger', 'cavity', 'end']
# 阈值设置
threshold:
  iou: 0.45
  confidence: 0.6
# 计算设备
# - cpu
# - 0 <- 使用GPU
device: '0'