// Generated by gencpp from file magmed_msgs/CtrlTwist.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_CTRLTWIST_H
#define MAGMED_MSGS_MESSAGE_CTRLTWIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace magmed_msgs
{
template <class ContainerAllocator>
struct CtrlTwist_
{
  typedef CtrlTwist_<ContainerAllocator> Type;

  CtrlTwist_()
    : psi(0.0)
    , p()  {
      p.assign(0.0);
  }
  CtrlTwist_(const ContainerAllocator& _alloc)
    : psi(0.0)
    , p()  {
  (void)_alloc;
      p.assign(0.0);
  }



   typedef double _psi_type;
  _psi_type psi;

   typedef boost::array<double, 3>  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::magmed_msgs::CtrlTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::CtrlTwist_<ContainerAllocator> const> ConstPtr;

}; // struct CtrlTwist_

typedef ::magmed_msgs::CtrlTwist_<std::allocator<void> > CtrlTwist;

typedef boost::shared_ptr< ::magmed_msgs::CtrlTwist > CtrlTwistPtr;
typedef boost::shared_ptr< ::magmed_msgs::CtrlTwist const> CtrlTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::CtrlTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::CtrlTwist_<ContainerAllocator1> & lhs, const ::magmed_msgs::CtrlTwist_<ContainerAllocator2> & rhs)
{
  return lhs.psi == rhs.psi &&
    lhs.p == rhs.p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::CtrlTwist_<ContainerAllocator1> & lhs, const ::magmed_msgs::CtrlTwist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::CtrlTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::CtrlTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::CtrlTwist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76917cdec57096cc983b4e09ed694109";
  }

  static const char* value(const ::magmed_msgs::CtrlTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76917cdec57096ccULL;
  static const uint64_t static_value2 = 0x983b4e09ed694109ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/CtrlTwist";
  }

  static const char* value(const ::magmed_msgs::CtrlTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 psi\n"
"float64[3] p\n"
;
  }

  static const char* value(const ::magmed_msgs::CtrlTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.psi);
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CtrlTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::CtrlTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::CtrlTwist_<ContainerAllocator>& v)
  {
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
    s << indent << "p[]" << std::endl;
    for (size_t i = 0; i < v.p.size(); ++i)
    {
      s << indent << "  p[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.p[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_CTRLTWIST_H
