// Generated by gencpp from file magmed_msgs/GetRobotStateResponse.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_GETROBOTSTATERESPONSE_H
#define MAGMED_MSGS_MESSAGE_GETROBOTSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace magmed_msgs
{
template <class ContainerAllocator>
struct GetRobotStateResponse_
{
  typedef GetRobotStateResponse_<ContainerAllocator> Type;

  GetRobotStateResponse_()
    : response(0)  {
    }
  GetRobotStateResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef int32_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRobotStateResponse_

typedef ::magmed_msgs::GetRobotStateResponse_<std::allocator<void> > GetRobotStateResponse;

typedef boost::shared_ptr< ::magmed_msgs::GetRobotStateResponse > GetRobotStateResponsePtr;
typedef boost::shared_ptr< ::magmed_msgs::GetRobotStateResponse const> GetRobotStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator1> & lhs, const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator1> & lhs, const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f45f68e2feefb1307598e828e260b7d7";
  }

  static const char* value(const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf45f68e2feefb130ULL;
  static const uint64_t static_value2 = 0x7598e828e260b7d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/GetRobotStateResponse";
  }

  static const char* value(const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 response\n"
;
  }

  static const char* value(const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRobotStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::GetRobotStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<int32_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_GETROBOTSTATERESPONSE_H
