// Generated by gencpp from file magmed_msgs/GetRobotState.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_GETROBOTSTATE_H
#define MAGMED_MSGS_MESSAGE_GETROBOTSTATE_H

#include <ros/service_traits.h>


#include <magmed_msgs/GetRobotStateRequest.h>
#include <magmed_msgs/GetRobotStateResponse.h>


namespace magmed_msgs
{

struct GetRobotState
{

typedef GetRobotStateRequest Request;
typedef GetRobotStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotState
} // namespace magmed_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::magmed_msgs::GetRobotState > {
  static const char* value()
  {
    return "51edd9dfd50014fde2b589cbf77706aa";
  }

  static const char* value(const ::magmed_msgs::GetRobotState&) { return value(); }
};

template<>
struct DataType< ::magmed_msgs::GetRobotState > {
  static const char* value()
  {
    return "magmed_msgs/GetRobotState";
  }

  static const char* value(const ::magmed_msgs::GetRobotState&) { return value(); }
};


// service_traits::MD5Sum< ::magmed_msgs::GetRobotStateRequest> should match
// service_traits::MD5Sum< ::magmed_msgs::GetRobotState >
template<>
struct MD5Sum< ::magmed_msgs::GetRobotStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::magmed_msgs::GetRobotState >::value();
  }
  static const char* value(const ::magmed_msgs::GetRobotStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::magmed_msgs::GetRobotStateRequest> should match
// service_traits::DataType< ::magmed_msgs::GetRobotState >
template<>
struct DataType< ::magmed_msgs::GetRobotStateRequest>
{
  static const char* value()
  {
    return DataType< ::magmed_msgs::GetRobotState >::value();
  }
  static const char* value(const ::magmed_msgs::GetRobotStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::magmed_msgs::GetRobotStateResponse> should match
// service_traits::MD5Sum< ::magmed_msgs::GetRobotState >
template<>
struct MD5Sum< ::magmed_msgs::GetRobotStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::magmed_msgs::GetRobotState >::value();
  }
  static const char* value(const ::magmed_msgs::GetRobotStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::magmed_msgs::GetRobotStateResponse> should match
// service_traits::DataType< ::magmed_msgs::GetRobotState >
template<>
struct DataType< ::magmed_msgs::GetRobotStateResponse>
{
  static const char* value()
  {
    return DataType< ::magmed_msgs::GetRobotState >::value();
  }
  static const char* value(const ::magmed_msgs::GetRobotStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_GETROBOTSTATE_H
