// Generated by gencpp from file magmed_msgs/JoyRef.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_JOYREF_H
#define MAGMED_MSGS_MESSAGE_JOYREF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <magmed_msgs/RefPhi.h>
#include <magmed_msgs/RefTheta.h>

namespace magmed_msgs
{
template <class ContainerAllocator>
struct JoyRef_
{
  typedef JoyRef_<ContainerAllocator> Type;

  JoyRef_()
    : header()
    , refPhi()
    , refTheta()  {
    }
  JoyRef_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , refPhi(_alloc)
    , refTheta(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::magmed_msgs::RefPhi_<ContainerAllocator>  _refPhi_type;
  _refPhi_type refPhi;

   typedef  ::magmed_msgs::RefTheta_<ContainerAllocator>  _refTheta_type;
  _refTheta_type refTheta;





  typedef boost::shared_ptr< ::magmed_msgs::JoyRef_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::JoyRef_<ContainerAllocator> const> ConstPtr;

}; // struct JoyRef_

typedef ::magmed_msgs::JoyRef_<std::allocator<void> > JoyRef;

typedef boost::shared_ptr< ::magmed_msgs::JoyRef > JoyRefPtr;
typedef boost::shared_ptr< ::magmed_msgs::JoyRef const> JoyRefConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::JoyRef_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::JoyRef_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::JoyRef_<ContainerAllocator1> & lhs, const ::magmed_msgs::JoyRef_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.refPhi == rhs.refPhi &&
    lhs.refTheta == rhs.refTheta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::JoyRef_<ContainerAllocator1> & lhs, const ::magmed_msgs::JoyRef_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::JoyRef_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::JoyRef_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::JoyRef_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea53e564f4388a7ea7a788d618611b29";
  }

  static const char* value(const ::magmed_msgs::JoyRef_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea53e564f4388a7eULL;
  static const uint64_t static_value2 = 0xa7a788d618611b29ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/JoyRef";
  }

  static const char* value(const ::magmed_msgs::JoyRef_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"RefPhi refPhi \n"
"RefTheta refTheta\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: magmed_msgs/RefPhi\n"
"float64 phi\n"
"float64 dphi\n"
"================================================================================\n"
"MSG: magmed_msgs/RefTheta\n"
"float64 theta\n"
"float64 dtheta\n"
;
  }

  static const char* value(const ::magmed_msgs::JoyRef_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.refPhi);
      stream.next(m.refTheta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoyRef_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::JoyRef_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "refPhi: ";
    s << std::endl;
    Printer< ::magmed_msgs::RefPhi_<ContainerAllocator> >::stream(s, indent + "  ", v.refPhi);
    s << indent << "refTheta: ";
    s << std::endl;
    Printer< ::magmed_msgs::RefTheta_<ContainerAllocator> >::stream(s, indent + "  ", v.refTheta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_JOYREF_H
