// Generated by gencpp from file magmed_msgs/JoyRef.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_JOYREF_H
#define MAGMED_MSGS_MESSAGE_JOYREF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace magmed_msgs
{
template <class ContainerAllocator>
struct JoyRef_
{
  typedef JoyRef_<ContainerAllocator> Type;

  JoyRef_()
    : header()
    , theta(0.0)
    , thetadot(0.0)
    , phi(0.0)
    , phidot(0.0)  {
    }
  JoyRef_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , theta(0.0)
    , thetadot(0.0)
    , phi(0.0)
    , phidot(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _thetadot_type;
  _thetadot_type thetadot;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _phidot_type;
  _phidot_type phidot;





  typedef boost::shared_ptr< ::magmed_msgs::JoyRef_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::JoyRef_<ContainerAllocator> const> ConstPtr;

}; // struct JoyRef_

typedef ::magmed_msgs::JoyRef_<std::allocator<void> > JoyRef;

typedef boost::shared_ptr< ::magmed_msgs::JoyRef > JoyRefPtr;
typedef boost::shared_ptr< ::magmed_msgs::JoyRef const> JoyRefConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::JoyRef_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::JoyRef_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::JoyRef_<ContainerAllocator1> & lhs, const ::magmed_msgs::JoyRef_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.theta == rhs.theta &&
    lhs.thetadot == rhs.thetadot &&
    lhs.phi == rhs.phi &&
    lhs.phidot == rhs.phidot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::JoyRef_<ContainerAllocator1> & lhs, const ::magmed_msgs::JoyRef_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::JoyRef_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::JoyRef_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::JoyRef_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa9cd8cd2e3cd0a81e9dae62d67c6a55";
  }

  static const char* value(const ::magmed_msgs::JoyRef_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa9cd8cd2e3cd0a8ULL;
  static const uint64_t static_value2 = 0x1e9dae62d67c6a55ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/JoyRef";
  }

  static const char* value(const ::magmed_msgs::JoyRef_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 theta\n"
"float64 thetadot\n"
"float64 phi\n"
"float64 phidot\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::magmed_msgs::JoyRef_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::JoyRef_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.theta);
      stream.next(m.thetadot);
      stream.next(m.phi);
      stream.next(m.phidot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoyRef_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::JoyRef_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::JoyRef_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "thetadot: ";
    Printer<double>::stream(s, indent + "  ", v.thetadot);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "phidot: ";
    Printer<double>::stream(s, indent + "  ", v.phidot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_JOYREF_H
