// Generated by gencpp from file magmed_msgs/MagPose.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_MAGPOSE_H
#define MAGMED_MSGS_MESSAGE_MAGPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace magmed_msgs
{
template <class ContainerAllocator>
struct MagPose_
{
  typedef MagPose_<ContainerAllocator> Type;

  MagPose_()
    : psi(0.0)
    , pos()  {
      pos.assign(0.0);
  }
  MagPose_(const ContainerAllocator& _alloc)
    : psi(0.0)
    , pos()  {
  (void)_alloc;
      pos.assign(0.0);
  }



   typedef double _psi_type;
  _psi_type psi;

   typedef boost::array<double, 3>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::magmed_msgs::MagPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::MagPose_<ContainerAllocator> const> ConstPtr;

}; // struct MagPose_

typedef ::magmed_msgs::MagPose_<std::allocator<void> > MagPose;

typedef boost::shared_ptr< ::magmed_msgs::MagPose > MagPosePtr;
typedef boost::shared_ptr< ::magmed_msgs::MagPose const> MagPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::MagPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::MagPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::MagPose_<ContainerAllocator1> & lhs, const ::magmed_msgs::MagPose_<ContainerAllocator2> & rhs)
{
  return lhs.psi == rhs.psi &&
    lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::MagPose_<ContainerAllocator1> & lhs, const ::magmed_msgs::MagPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::MagPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::MagPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::MagPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::MagPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::MagPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::MagPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::MagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad8b136153ecd61f300fa21020162f97";
  }

  static const char* value(const ::magmed_msgs::MagPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad8b136153ecd61fULL;
  static const uint64_t static_value2 = 0x300fa21020162f97ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::MagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/MagPose";
  }

  static const char* value(const ::magmed_msgs::MagPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::MagPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 psi\n"
"float64[3] pos\n"
;
  }

  static const char* value(const ::magmed_msgs::MagPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::MagPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.psi);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::MagPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::MagPose_<ContainerAllocator>& v)
  {
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_MAGPOSE_H
