// Generated by gencpp from file magmed_msgs/RefPhi.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_REFPHI_H
#define MAGMED_MSGS_MESSAGE_REFPHI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace magmed_msgs
{
template <class ContainerAllocator>
struct RefPhi_
{
  typedef RefPhi_<ContainerAllocator> Type;

  RefPhi_()
    : phi(0.0)
    , dphi(0.0)  {
    }
  RefPhi_(const ContainerAllocator& _alloc)
    : phi(0.0)
    , dphi(0.0)  {
  (void)_alloc;
    }



   typedef double _phi_type;
  _phi_type phi;

   typedef double _dphi_type;
  _dphi_type dphi;





  typedef boost::shared_ptr< ::magmed_msgs::RefPhi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::RefPhi_<ContainerAllocator> const> ConstPtr;

}; // struct RefPhi_

typedef ::magmed_msgs::RefPhi_<std::allocator<void> > RefPhi;

typedef boost::shared_ptr< ::magmed_msgs::RefPhi > RefPhiPtr;
typedef boost::shared_ptr< ::magmed_msgs::RefPhi const> RefPhiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::RefPhi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::RefPhi_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::RefPhi_<ContainerAllocator1> & lhs, const ::magmed_msgs::RefPhi_<ContainerAllocator2> & rhs)
{
  return lhs.phi == rhs.phi &&
    lhs.dphi == rhs.dphi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::RefPhi_<ContainerAllocator1> & lhs, const ::magmed_msgs::RefPhi_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RefPhi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RefPhi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RefPhi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RefPhi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RefPhi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RefPhi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::RefPhi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55e8d7deb213bddd90abc0b338391bbc";
  }

  static const char* value(const ::magmed_msgs::RefPhi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55e8d7deb213bdddULL;
  static const uint64_t static_value2 = 0x90abc0b338391bbcULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::RefPhi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/RefPhi";
  }

  static const char* value(const ::magmed_msgs::RefPhi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::RefPhi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 phi\n"
"float64 dphi\n"
;
  }

  static const char* value(const ::magmed_msgs::RefPhi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::RefPhi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phi);
      stream.next(m.dphi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RefPhi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::RefPhi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::RefPhi_<ContainerAllocator>& v)
  {
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "dphi: ";
    Printer<double>::stream(s, indent + "  ", v.dphi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_REFPHI_H
