// Generated by gencpp from file magmed_msgs/RefTheta.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_REFTHETA_H
#define MAGMED_MSGS_MESSAGE_REFTHETA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace magmed_msgs
{
template <class ContainerAllocator>
struct RefTheta_
{
  typedef RefTheta_<ContainerAllocator> Type;

  RefTheta_()
    : theta(0.0)
    , dtheta(0.0)  {
    }
  RefTheta_(const ContainerAllocator& _alloc)
    : theta(0.0)
    , dtheta(0.0)  {
  (void)_alloc;
    }



   typedef double _theta_type;
  _theta_type theta;

   typedef double _dtheta_type;
  _dtheta_type dtheta;





  typedef boost::shared_ptr< ::magmed_msgs::RefTheta_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::RefTheta_<ContainerAllocator> const> ConstPtr;

}; // struct RefTheta_

typedef ::magmed_msgs::RefTheta_<std::allocator<void> > RefTheta;

typedef boost::shared_ptr< ::magmed_msgs::RefTheta > RefThetaPtr;
typedef boost::shared_ptr< ::magmed_msgs::RefTheta const> RefThetaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::RefTheta_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::RefTheta_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::RefTheta_<ContainerAllocator1> & lhs, const ::magmed_msgs::RefTheta_<ContainerAllocator2> & rhs)
{
  return lhs.theta == rhs.theta &&
    lhs.dtheta == rhs.dtheta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::RefTheta_<ContainerAllocator1> & lhs, const ::magmed_msgs::RefTheta_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RefTheta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RefTheta_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RefTheta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RefTheta_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RefTheta_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RefTheta_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::RefTheta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4963a90c97bbf7fdb1b9c9e9a7d1576";
  }

  static const char* value(const ::magmed_msgs::RefTheta_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4963a90c97bbf7fULL;
  static const uint64_t static_value2 = 0xdb1b9c9e9a7d1576ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::RefTheta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/RefTheta";
  }

  static const char* value(const ::magmed_msgs::RefTheta_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::RefTheta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 theta\n"
"float64 dtheta\n"
;
  }

  static const char* value(const ::magmed_msgs::RefTheta_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::RefTheta_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.dtheta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RefTheta_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::RefTheta_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::RefTheta_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "dtheta: ";
    Printer<double>::stream(s, indent + "  ", v.dtheta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_REFTHETA_H
