// Generated by gencpp from file magmed_msgs/RoboStates.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_ROBOSTATES_H
#define MAGMED_MSGS_MESSAGE_ROBOSTATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace magmed_msgs
{
template <class ContainerAllocator>
struct RoboStates_
{
  typedef RoboStates_<ContainerAllocator> Type;

  RoboStates_()
    : header()  {
    }
  RoboStates_(const ContainerAllocator& _alloc)
    : header(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INIT)
  #undef INIT
#endif
#if defined(_WIN32) && defined(CTRL)
  #undef CTRL
#endif
#if defined(_WIN32) && defined(TERM)
  #undef TERM
#endif

  enum {
    INIT = 0,
    CTRL = 1,
    TERM = 2,
  };


  typedef boost::shared_ptr< ::magmed_msgs::RoboStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::RoboStates_<ContainerAllocator> const> ConstPtr;

}; // struct RoboStates_

typedef ::magmed_msgs::RoboStates_<std::allocator<void> > RoboStates;

typedef boost::shared_ptr< ::magmed_msgs::RoboStates > RoboStatesPtr;
typedef boost::shared_ptr< ::magmed_msgs::RoboStates const> RoboStatesConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::RoboStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::RoboStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::RoboStates_<ContainerAllocator1> & lhs, const ::magmed_msgs::RoboStates_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::RoboStates_<ContainerAllocator1> & lhs, const ::magmed_msgs::RoboStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RoboStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RoboStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RoboStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RoboStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RoboStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RoboStates_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::RoboStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4437f8da4929f4c392a982caafd44e62";
  }

  static const char* value(const ::magmed_msgs::RoboStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4437f8da4929f4c3ULL;
  static const uint64_t static_value2 = 0x92a982caafd44e62ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::RoboStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/RoboStates";
  }

  static const char* value(const ::magmed_msgs::RoboStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::RoboStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8  INIT = 0    # 初始化状态\n"
"int8  CTRL = 1    # 控制状态\n"
"int8  TERM = 2    # 终止状态\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::magmed_msgs::RoboStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::RoboStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoboStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::RoboStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::RoboStates_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_ROBOSTATES_H
