// Generated by gencpp from file magmed_msgs/RoboJoints.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_ROBOJOINTS_H
#define MAGMED_MSGS_MESSAGE_ROBOJOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace magmed_msgs
{
template <class ContainerAllocator>
struct RoboJoints_
{
  typedef RoboJoints_<ContainerAllocator> Type;

  RoboJoints_()
    : header()
    , joints()  {
    }
  RoboJoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::magmed_msgs::RoboJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::RoboJoints_<ContainerAllocator> const> ConstPtr;

}; // struct RoboJoints_

typedef ::magmed_msgs::RoboJoints_<std::allocator<void> > RoboJoints;

typedef boost::shared_ptr< ::magmed_msgs::RoboJoints > RoboJointsPtr;
typedef boost::shared_ptr< ::magmed_msgs::RoboJoints const> RoboJointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::RoboJoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::RoboJoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::RoboJoints_<ContainerAllocator1> & lhs, const ::magmed_msgs::RoboJoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::RoboJoints_<ContainerAllocator1> & lhs, const ::magmed_msgs::RoboJoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::RoboJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::RoboJoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::RoboJoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b092ab83740cca6bcafed6a3ef867084";
  }

  static const char* value(const ::magmed_msgs::RoboJoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb092ab83740cca6bULL;
  static const uint64_t static_value2 = 0xcafed6a3ef867084ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/RoboJoints";
  }

  static const char* value(const ::magmed_msgs::RoboJoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] joints\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::magmed_msgs::RoboJoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoboJoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::RoboJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::RoboJoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_ROBOJOINTS_H
