// Generated by gencpp from file magmed_msgs/SelfCollisionCheck.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECK_H
#define MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECK_H

#include <ros/service_traits.h>


#include <magmed_msgs/SelfCollisionCheckRequest.h>
#include <magmed_msgs/SelfCollisionCheckResponse.h>


namespace magmed_msgs
{

struct SelfCollisionCheck
{

typedef SelfCollisionCheckRequest Request;
typedef SelfCollisionCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SelfCollisionCheck
} // namespace magmed_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::magmed_msgs::SelfCollisionCheck > {
  static const char* value()
  {
    return "7060f063846e94f79170ebac9812a07a";
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheck&) { return value(); }
};

template<>
struct DataType< ::magmed_msgs::SelfCollisionCheck > {
  static const char* value()
  {
    return "magmed_msgs/SelfCollisionCheck";
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheck&) { return value(); }
};


// service_traits::MD5Sum< ::magmed_msgs::SelfCollisionCheckRequest> should match
// service_traits::MD5Sum< ::magmed_msgs::SelfCollisionCheck >
template<>
struct MD5Sum< ::magmed_msgs::SelfCollisionCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::magmed_msgs::SelfCollisionCheck >::value();
  }
  static const char* value(const ::magmed_msgs::SelfCollisionCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::magmed_msgs::SelfCollisionCheckRequest> should match
// service_traits::DataType< ::magmed_msgs::SelfCollisionCheck >
template<>
struct DataType< ::magmed_msgs::SelfCollisionCheckRequest>
{
  static const char* value()
  {
    return DataType< ::magmed_msgs::SelfCollisionCheck >::value();
  }
  static const char* value(const ::magmed_msgs::SelfCollisionCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::magmed_msgs::SelfCollisionCheckResponse> should match
// service_traits::MD5Sum< ::magmed_msgs::SelfCollisionCheck >
template<>
struct MD5Sum< ::magmed_msgs::SelfCollisionCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::magmed_msgs::SelfCollisionCheck >::value();
  }
  static const char* value(const ::magmed_msgs::SelfCollisionCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::magmed_msgs::SelfCollisionCheckResponse> should match
// service_traits::DataType< ::magmed_msgs::SelfCollisionCheck >
template<>
struct DataType< ::magmed_msgs::SelfCollisionCheckResponse>
{
  static const char* value()
  {
    return DataType< ::magmed_msgs::SelfCollisionCheck >::value();
  }
  static const char* value(const ::magmed_msgs::SelfCollisionCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECK_H
