// Generated by gencpp from file magmed_msgs/SelfCollisionCheckRequest.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECKREQUEST_H
#define MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <magmed_msgs/RoboJoints.h>

namespace magmed_msgs
{
template <class ContainerAllocator>
struct SelfCollisionCheckRequest_
{
  typedef SelfCollisionCheckRequest_<ContainerAllocator> Type;

  SelfCollisionCheckRequest_()
    : joints()  {
    }
  SelfCollisionCheckRequest_(const ContainerAllocator& _alloc)
    : joints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::magmed_msgs::RoboJoints_<ContainerAllocator>  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SelfCollisionCheckRequest_

typedef ::magmed_msgs::SelfCollisionCheckRequest_<std::allocator<void> > SelfCollisionCheckRequest;

typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckRequest > SelfCollisionCheckRequestPtr;
typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckRequest const> SelfCollisionCheckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator1> & lhs, const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator1> & lhs, const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbf85f6e82ce9a948d141e2b479a32b3";
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbf85f6e82ce9a94ULL;
  static const uint64_t static_value2 = 0x8d141e2b479a32b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/SelfCollisionCheckRequest";
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboJoints joints\n"
"\n"
"================================================================================\n"
"MSG: magmed_msgs/RoboJoints\n"
"Header header\n"
"float64[] joints\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelfCollisionCheckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::SelfCollisionCheckRequest_<ContainerAllocator>& v)
  {
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::magmed_msgs::RoboJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECKREQUEST_H
