// Generated by gencpp from file magmed_msgs/SelfCollisionCheckResponse.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECKRESPONSE_H
#define MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace magmed_msgs
{
template <class ContainerAllocator>
struct SelfCollisionCheckResponse_
{
  typedef SelfCollisionCheckResponse_<ContainerAllocator> Type;

  SelfCollisionCheckResponse_()
    : checkResult(false)  {
    }
  SelfCollisionCheckResponse_(const ContainerAllocator& _alloc)
    : checkResult(false)  {
  (void)_alloc;
    }



   typedef uint8_t _checkResult_type;
  _checkResult_type checkResult;





  typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SelfCollisionCheckResponse_

typedef ::magmed_msgs::SelfCollisionCheckResponse_<std::allocator<void> > SelfCollisionCheckResponse;

typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckResponse > SelfCollisionCheckResponsePtr;
typedef boost::shared_ptr< ::magmed_msgs::SelfCollisionCheckResponse const> SelfCollisionCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator1> & lhs, const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator2> & rhs)
{
  return lhs.checkResult == rhs.checkResult;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator1> & lhs, const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3429e6e099a21a76bf78e62a4b36ad3";
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3429e6e099a21a7ULL;
  static const uint64_t static_value2 = 0x6bf78e62a4b36ad3ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/SelfCollisionCheckResponse";
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool checkResult\n"
;
  }

  static const char* value(const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.checkResult);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelfCollisionCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::SelfCollisionCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "checkResult: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checkResult);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_SELFCOLLISIONCHECKRESPONSE_H
