// Generated by gencpp from file magmed_msgs/TipAngle.msg
// DO NOT EDIT!


#ifndef MAGMED_MSGS_MESSAGE_TIPANGLE_H
#define MAGMED_MSGS_MESSAGE_TIPANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace magmed_msgs
{
template <class ContainerAllocator>
struct TipAngle_
{
  typedef TipAngle_<ContainerAllocator> Type;

  TipAngle_()
    : header()
    , tipAngle(0.0)  {
    }
  TipAngle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tipAngle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _tipAngle_type;
  _tipAngle_type tipAngle;





  typedef boost::shared_ptr< ::magmed_msgs::TipAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magmed_msgs::TipAngle_<ContainerAllocator> const> ConstPtr;

}; // struct TipAngle_

typedef ::magmed_msgs::TipAngle_<std::allocator<void> > TipAngle;

typedef boost::shared_ptr< ::magmed_msgs::TipAngle > TipAnglePtr;
typedef boost::shared_ptr< ::magmed_msgs::TipAngle const> TipAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magmed_msgs::TipAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magmed_msgs::TipAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magmed_msgs::TipAngle_<ContainerAllocator1> & lhs, const ::magmed_msgs::TipAngle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tipAngle == rhs.tipAngle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magmed_msgs::TipAngle_<ContainerAllocator1> & lhs, const ::magmed_msgs::TipAngle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magmed_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::TipAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magmed_msgs::TipAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::TipAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magmed_msgs::TipAngle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::TipAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magmed_msgs::TipAngle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magmed_msgs::TipAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53e2c53db502ae3cd8c298da558777c3";
  }

  static const char* value(const ::magmed_msgs::TipAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53e2c53db502ae3cULL;
  static const uint64_t static_value2 = 0xd8c298da558777c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::magmed_msgs::TipAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magmed_msgs/TipAngle";
  }

  static const char* value(const ::magmed_msgs::TipAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magmed_msgs::TipAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 tipAngle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::magmed_msgs::TipAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magmed_msgs::TipAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tipAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TipAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magmed_msgs::TipAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magmed_msgs::TipAngle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tipAngle: ";
    Printer<double>::stream(s, indent + "  ", v.tipAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGMED_MSGS_MESSAGE_TIPANGLE_H
